site_name: Test MKdocs with nesi-intro material
site_url: https://dinindusenanayake.github.io/nesi_introductory_custom/

nav:
  - Home: index.md
  - Getting started:
    - Slurm example: example.md
    - R example: foreachparallel.md
